# CMake generated Testfile for 
# Source directory: /Users/jak/src/daw
# Build directory: /Users/jak/src/daw/build-asan
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(contract_freshness "/Users/jak/src/daw/tools/contract_freshness_check.sh")
set_tests_properties(contract_freshness PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;459;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(contract_layout "/Users/jak/src/daw/tools/contract_layout_check.sh")
set_tests_properties(contract_layout PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;465;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(bridge_layout "cargo" "test" "--manifest-path" "/Users/jak/src/daw/ui/Cargo.toml" "-p" "daw-bridge")
set_tests_properties(bridge_layout PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;474;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(patcher_resolution "/Users/jak/src/daw/build-asan/patcher_tests")
set_tests_properties(patcher_resolution PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;479;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(patcher_graph_edits "/Users/jak/src/daw/build-asan/patcher_graph_tests")
set_tests_properties(patcher_graph_edits PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;484;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(project_file_round_trip "/Users/jak/src/daw/build-asan/project_file_tests" "/Users/jak/src/daw/presets/projects")
set_tests_properties(project_file_round_trip PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;489;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(waveform_pyramid "/Users/jak/src/daw/build-asan/waveform_pyramid_tests")
set_tests_properties(waveform_pyramid PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;494;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(waveform_store "/Users/jak/src/daw/build-asan/waveform_store_tests")
set_tests_properties(waveform_store PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;499;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(event_ring_mpsc "/Users/jak/src/daw/build-asan/event_ring_mpsc_tests")
set_tests_properties(event_ring_mpsc PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;504;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(op_registry "bash" "/Users/jak/src/daw/tools/op_registry_check.sh")
set_tests_properties(op_registry PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;513;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(lint "bash" "/Users/jak/src/daw/tools/lint_check.sh")
set_tests_properties(lint PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;518;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(markers "/Users/jak/src/daw/build-asan/markers_tests")
set_tests_properties(markers PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;523;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(sampler_envelope "/Users/jak/src/daw/build-asan/sampler_envelope_tests")
set_tests_properties(sampler_envelope PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;528;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(sampler_check "bash" "/Users/jak/src/daw/tools/sampler_check.sh")
set_tests_properties(sampler_check PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;533;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(sampler_load "bash" "/Users/jak/src/daw/tools/sampler_load_check.sh")
set_tests_properties(sampler_load PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;538;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(module "bash" "/Users/jak/src/daw/tools/module_check.sh")
set_tests_properties(module PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;543;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(sampler_chop "bash" "/Users/jak/src/daw/tools/sampler_chop_check.sh")
set_tests_properties(sampler_chop PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;548;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(sampler_slice_stability "bash" "/Users/jak/src/daw/tools/sampler_slice_stability_check.sh")
set_tests_properties(sampler_slice_stability PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;553;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(sampler_sound_address "bash" "/Users/jak/src/daw/tools/sampler_sound_address_check.sh")
set_tests_properties(sampler_sound_address PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;558;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(sampler_kit "bash" "/Users/jak/src/daw/tools/sampler_kit_check.sh")
set_tests_properties(sampler_kit PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;563;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(sampler_determinism "bash" "/Users/jak/src/daw/tools/sampler_determinism_check.sh")
set_tests_properties(sampler_determinism PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;568;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(sampler_stem "bash" "/Users/jak/src/daw/tools/sampler_stem_check.sh")
set_tests_properties(sampler_stem PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;574;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(producer_load "bash" "/Users/jak/src/daw/tools/producer_load_check.sh" "8")
set_tests_properties(producer_load PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;581;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(patcher_plays_sampler "bash" "/Users/jak/src/daw/tools/patcher_plays_sampler_check.sh")
set_tests_properties(patcher_plays_sampler PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;588;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(realtime_pool "bash" "/Users/jak/src/daw/tools/realtime_pool_check.sh" "24")
set_tests_properties(realtime_pool PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;597;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(bulk_carrier "bash" "/Users/jak/src/daw/tools/bulk_carrier_check.sh")
set_tests_properties(bulk_carrier PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;604;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(sampler_envelope_write "bash" "/Users/jak/src/daw/tools/sampler_envelope_write_check.sh")
set_tests_properties(sampler_envelope_write PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;611;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(row_ops_write "bash" "/Users/jak/src/daw/tools/row_ops_write_check.sh")
set_tests_properties(row_ops_write PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;617;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(render_pool "bash" "/Users/jak/src/daw/tools/render_pool_check.sh")
set_tests_properties(render_pool PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;623;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(sampler_state "/Users/jak/src/daw/build-asan/sampler_state_tests")
set_tests_properties(sampler_state PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;628;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(sampler_voice "/Users/jak/src/daw/build-asan/sampler_voice_tests")
set_tests_properties(sampler_voice PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;633;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(zip_container "/Users/jak/src/daw/build-asan/zip_container_tests")
set_tests_properties(zip_container PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;638;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(sampler_slice "/Users/jak/src/daw/build-asan/sampler_slice_tests")
set_tests_properties(sampler_slice PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;643;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(sampler_dsp "/Users/jak/src/daw/build-asan/sampler_dsp_tests")
set_tests_properties(sampler_dsp PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;648;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(sampler_engine "/Users/jak/src/daw/build-asan/sampler_engine_tests")
set_tests_properties(sampler_engine PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;653;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(placement_adds "/Users/jak/src/daw/build-asan/placement_adds_tests")
set_tests_properties(placement_adds PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;658;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(time_signature "/Users/jak/src/daw/build-asan/time_signature_tests")
set_tests_properties(time_signature PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;663;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(tempo_integral "/Users/jak/src/daw/build-asan/tempo_integral_tests")
set_tests_properties(tempo_integral PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;668;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(lane_quantize "/Users/jak/src/daw/build-asan/lane_quantize_tests")
set_tests_properties(lane_quantize PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;673;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(clip_grid "/Users/jak/src/daw/build-asan/clip_grid_tests")
set_tests_properties(clip_grid PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;678;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(waveform_fixture "/Users/jak/src/daw/build-asan/waveform_fixture_tests" "/Users/jak/src/daw/presets/audio")
set_tests_properties(waveform_fixture PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;683;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(device_chain_defaults "/Users/jak/src/daw/build-asan/device_chain_tests")
set_tests_properties(device_chain_defaults PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;688;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(device_chain_ui "/Users/jak/src/daw/build-asan/device_chain_ui_tests")
set_tests_properties(device_chain_ui PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;693;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(device_chain_ui_live "/Users/jak/src/daw/build-asan/device_chain_ui_live_tests")
set_tests_properties(device_chain_ui_live PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;698;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(phase2_impulse "/Users/jak/src/daw/build-asan/phase2_tests" "--test" "impulse" "--plugin" "/Users/jak/src/daw/build-asan/identity_plugin_artefacts/RelWithDebInfo/VST3/Identity.vst3")
set_tests_properties(phase2_impulse PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;719;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(phase2_param_priority "/Users/jak/src/daw/build-asan/phase2_tests" "--test" "param_priority" "--plugin" "/Users/jak/src/daw/build-asan/identity_plugin_artefacts/RelWithDebInfo/VST3/Identity.vst3")
set_tests_properties(phase2_param_priority PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;725;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(phase2_param_targeting "/Users/jak/src/daw/build-asan/phase2_tests" "--test" "param_targeting" "--plugin" "/Users/jak/src/daw/build-asan/identity_plugin_artefacts/RelWithDebInfo/VST3/Identity.vst3")
set_tests_properties(phase2_param_targeting PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;731;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(phase2_chaos "/Users/jak/src/daw/build-asan/phase2_tests" "--test" "chaos" "--plugin" "/Users/jak/src/daw/build-asan/identity_plugin_artefacts/RelWithDebInfo/VST3/Identity.vst3")
set_tests_properties(phase2_chaos PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;737;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(phase2_ui_visual "/Users/jak/src/daw/build-asan/phase2_tests" "--test" "ui_visual" "--plugin" "/Users/jak/src/daw/build-asan/identity_plugin_artefacts/RelWithDebInfo/VST3/Identity.vst3")
set_tests_properties(phase2_ui_visual PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;743;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(phase3_timebase "/Users/jak/src/daw/build-asan/phase3_tests" "--test" "timebase" "--plugin" "/Users/jak/src/daw/build-asan/identity_plugin_artefacts/RelWithDebInfo/VST3/Identity.vst3")
set_tests_properties(phase3_timebase PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;769;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(phase3_scheduler_ring "/Users/jak/src/daw/build-asan/phase3_tests" "--test" "scheduler_ring" "--plugin" "/Users/jak/src/daw/build-asan/identity_plugin_artefacts/RelWithDebInfo/VST3/Identity.vst3")
set_tests_properties(phase3_scheduler_ring PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;775;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(phase3_automation_ring "/Users/jak/src/daw/build-asan/phase3_tests" "--test" "automation_ring" "--plugin" "/Users/jak/src/daw/build-asan/identity_plugin_artefacts/RelWithDebInfo/VST3/Identity.vst3")
set_tests_properties(phase3_automation_ring PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;781;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(phase3_audio_region "/Users/jak/src/daw/build-asan/phase3_tests" "--test" "audio_region")
set_tests_properties(phase3_audio_region PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;787;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(audio_io "/Users/jak/src/daw/build-asan/audio_io_tests")
set_tests_properties(audio_io PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;792;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(phase3_harmony_quantize "/Users/jak/src/daw/build-asan/phase3_tests" "--test" "harmony_quantize")
set_tests_properties(phase3_harmony_quantize PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;797;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(phase3_chord_expansion "/Users/jak/src/daw/build-asan/phase3_tests" "--test" "chord_expansion")
set_tests_properties(phase3_chord_expansion PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;802;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(phase3_humanize_determinism "/Users/jak/src/daw/build-asan/phase3_tests" "--test" "humanize_determinism")
set_tests_properties(phase3_humanize_determinism PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;807;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(phase3_harmony_order "/Users/jak/src/daw/build-asan/phase3_tests" "--test" "harmony_order")
set_tests_properties(phase3_harmony_order PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;812;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(phase3_snapshot "/Users/jak/src/daw/build-asan/phase3_tests" "--test" "snapshot")
set_tests_properties(phase3_snapshot PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;817;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(phase3_undo_stack "/Users/jak/src/daw/build-asan/phase3_tests" "--test" "undo_stack")
set_tests_properties(phase3_undo_stack PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;822;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(phase3_note_duration "/Users/jak/src/daw/build-asan/phase3_tests" "--test" "note_duration")
set_tests_properties(phase3_note_duration PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;827;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(phase3_row_op_probability "/Users/jak/src/daw/build-asan/phase3_tests" "--test" "row_op_probability")
set_tests_properties(phase3_row_op_probability PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;832;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(phase3_row_op_expand "/Users/jak/src/daw/build-asan/phase3_tests" "--test" "row_op_expand")
set_tests_properties(phase3_row_op_expand PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;837;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(phase3_placement_schedule "/Users/jak/src/daw/build-asan/phase3_tests" "--test" "placement_schedule")
set_tests_properties(phase3_placement_schedule PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;842;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(phase3_note_entry "/Users/jak/src/daw/build-asan/phase3_tests" "--test" "note_entry")
set_tests_properties(phase3_note_entry PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;847;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(phase3_resync_mismatch "/Users/jak/src/daw/build-asan/phase3_tests" "--test" "resync_mismatch")
set_tests_properties(phase3_resync_mismatch PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;852;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(phase3_pulse_full "/Users/jak/src/daw/build-asan/phase3_tests" "--test" "pulse_full" "--plugin" "/Users/jak/src/daw/build-asan/identity_plugin_artefacts/RelWithDebInfo/VST3/Identity.vst3")
set_tests_properties(phase3_pulse_full PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;857;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(phase3_note_off_full "/Users/jak/src/daw/build-asan/phase3_tests" "--test" "note_off_full" "--plugin" "/Users/jak/src/daw/build-asan/identity_plugin_artefacts/RelWithDebInfo/VST3/Identity.vst3")
set_tests_properties(phase3_note_off_full PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;863;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(phase3_resurrection_full "/Users/jak/src/daw/build-asan/phase3_tests" "--test" "resurrection_full" "--plugin" "/Users/jak/src/daw/build-asan/identity_plugin_artefacts/RelWithDebInfo/VST3/Identity.vst3")
set_tests_properties(phase3_resurrection_full PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;869;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
add_test(phase3_composition_full "/Users/jak/src/daw/build-asan/phase3_tests" "--test" "composition_full" "--plugin" "/Users/jak/src/daw/build-asan/identity_plugin_artefacts/RelWithDebInfo/VST3/Identity.vst3")
set_tests_properties(phase3_composition_full PROPERTIES  WORKING_DIRECTORY "/Users/jak/src/daw/build-asan" _BACKTRACE_TRIPLES "/Users/jak/src/daw/CMakeLists.txt;875;add_test;/Users/jak/src/daw/CMakeLists.txt;0;")
subdirs("juce")
