#!/usr/bin/env node
// Generate every consumer of the design tokens from tokens.json.
//
// Three targets, one source. The point of the Rust target is not that we ship a
// Rust frontend today — it is that the token pipeline stays kit-agnostic, so
// swapping the renderer never means re-typing colours. The measured cost of
// tokenising versus the design export's inline styles was -6% (1.41 vs 1.50 ms
// per keystroke at 64x16), so this is free.
//
//   node design/build-tokens.mjs
//     -> src/tokens.css        CSS custom properties (the web renderer)
//     -> design/out/theme.rs   a `const Theme` (any Rust renderer)
//     -> design/out/tokens.js  a plain object (a canvas renderer)

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const T = JSON.parse(readFileSync(join(here, 'tokens.json'), 'utf8'));

/** Resolve {"ref":"base.neutral.300"} against the token tree. */
function resolve(v) {
  if (v && typeof v === 'object' && typeof v.ref === 'string') {
    const hit = v.ref.split('.').reduce((o, k) => (o == null ? o : o[k]), T);
    if (hit === undefined) throw new Error(`unresolved token ref: ${v.ref}`);
    return resolve(hit);
  }
  return v;
}

/** Walk the token tree into flat [path, value] pairs, skipping $-prefixed
 *  metadata keys. Any $name is metadata, not just the literal `$comment` — a
 *  `$offGridComment` shipped a whole sentence into tokens.css as a variable. */
function flatten(node, path = [], out = []) {
  for (const [k, v] of Object.entries(node)) {
    if (k.startsWith('$')) continue;
    const p = [...path, k];
    if (v && typeof v === 'object' && !Array.isArray(v) && !('ref' in v)) flatten(v, p, out);
    else if (Array.isArray(v)) v.forEach((item, i) => out.push([[...p, String(i)], resolve(item)]));
    else out.push([p, resolve(v)]);
  }
  return out;
}

const kebab = (p) => p.join('-').replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const snake = (p) => p.join('_').replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase();

const pairs = flatten(T);
const px = (v) => (typeof v === 'number' ? `${v}px` : v);

// ---- CSS -------------------------------------------------------------------
const css = `/* GENERATED by design/build-tokens.mjs from design/tokens.json. Do not edit. */
:root {
${pairs.map(([p, v]) => `  --${kebab(p)}: ${px(v)};`).join('\n')}
}
`;
writeFileSync(join(root, 'src', 'tokens.css'), css);

// ---- Rust ------------------------------------------------------------------
// Colours become u32 0xAARRGGBB so any Rust renderer can consume them without a
// colour parser. Non-colour values are emitted as f32 or &str.
function toArgb(s) {
  const m = /^#([0-9a-f]{6})$/i.exec(s);
  if (m) return `0xff${m[1].toLowerCase()}`;
  const r = /^rgba?\(\s*([\d.]+)\s*,\s*([\d.]+)\s*,\s*([\d.]+)\s*(?:,\s*([\d.]+)\s*)?\)$/i.exec(s);
  if (!r) return null;
  const a = Math.round((r[4] === undefined ? 1 : +r[4]) * 255);
  const h = (n) => (+n & 255).toString(16).padStart(2, '0');
  return `0x${a.toString(16).padStart(2, '0')}${h(r[1])}${h(r[2])}${h(r[3])}`;
}
const rustLines = [];
for (const [p, v] of pairs) {
  const name = snake(p).toUpperCase();
  if (typeof v === 'number') rustLines.push(`    pub const ${name}: f32 = ${v.toFixed(1)};`);
  else {
    const argb = toArgb(String(v));
    if (argb) rustLines.push(`    pub const ${name}: u32 = ${argb};`);
    else rustLines.push(`    pub const ${name}: &str = ${JSON.stringify(v)};`);
  }
}
const rust = `// GENERATED by design/build-tokens.mjs from design/tokens.json. Do not edit.
// Colours are 0xAARRGGBB.
#[allow(dead_code)]
pub mod theme {
${rustLines.join('\n')}
}
`;
mkdirSync(join(here, 'out'), { recursive: true });
writeFileSync(join(here, 'out', 'theme.rs'), rust);

// ---- Plain JS object (canvas renderer) -------------------------------------
const obj = {};
for (const [p, v] of pairs) {
  let cur = obj;
  p.slice(0, -1).forEach((k) => (cur = cur[k] ??= {}));
  cur[p[p.length - 1]] = v;
}
writeFileSync(
  join(here, 'out', 'tokens.js'),
  `// GENERATED by design/build-tokens.mjs from design/tokens.json. Do not edit.\nexport default ${JSON.stringify(obj, null, 2)};\n`
);

console.log(`tokens: ${pairs.length} values -> src/tokens.css, design/out/theme.rs, design/out/tokens.js`);
