/**
 * FIVE SAMPLES, LOADED AND TRACKED THROUGH THE UI, RENDERED, AND COMPARED BYTE FOR BYTE.
 *
 * Owner's ask, verbatim: "another suite should load up a bunch of samples, track them _via the
 * ui_ and assert wav===golden".
 *
 * WHY BYTE EQUALITY IS AVAILABLE AT ALL. A realtime capture cannot be compared exactly — the
 * device clock, the underruns and where the capture window opens all move — which is why every
 * audio suite here so far measures onsets and peaks instead. The engine's OFFLINE RENDER
 * (`daw_engine --render <name>`) has no audio device and no wall clock: the pump waits for every
 * host to finish each block, so two renders of one project are byte-identical and
 * tools/offline_render_check.sh asserts exactly that. That determinism is what makes a WAV
 * golden possible, and this file re-asserts it locally rather than trusting it — a mismatch
 * against the golden has to be attributable to the change, not to a race.
 *
 * WHAT IS ACTUALLY UNDER TEST is the whole chain in one artefact: the console's `sampler` and
 * `load-sample` verbs, the slot the engine mints per load, the note entry that addresses those
 * slots by key, the save, the project format, the decode, the voice allocation, the envelope
 * mint, and the mix. Any of them changing changes the bytes. That is the point and also the
 * cost: this golden is SENSITIVE, and a diff means "look", not "something is broken".
 *
 * IT IS MACHINE-SPECIFIC, the same bargain the PNG goldens already make: the render is
 * deterministic for one build on one machine, not across builds. `--bless` after a deliberate
 * change, and read the four discriminating checks below before you do.
 *
 * FOUR THINGS MAKE THE COMPARISON MEAN SOMETHING, and without them "the wav equals the golden"
 * is the easiest check in the world to pass:
 *   1. the render is NOT SILENT — a golden of silence matches a broken engine forever;
 *   2. every sample is AUDIBLE IN ITS OWN WINDOW, so a render that dropped four of five voices
 *      cannot pass by being loud in one place;
 *   3. the render is REPEATABLE in this run, so a byte diff is the change and not a race;
 *   4. a DELIBERATELY DIFFERENT project renders DIFFERENT bytes — the comparison discriminates.
 */

import { chromium } from 'playwright';
import { startStack } from './stack.mjs';
import { writeFileSync, readFileSync, existsSync, mkdirSync, unlinkSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const BLESS = process.argv.includes('--bless');
const here = dirname(fileURLToPath(import.meta.url));
const ROOT = join(here, '..', '..');
const BASE = join(here, 'baselines');
const GOLDEN = join(BASE, 'sampler-render.wav');

let pass = 0, fail = 0;
const check = (ok, what, detail) => {
  if (ok) { pass++; console.log('  PASS ', what); }
  else { fail++; console.log('  FAIL ', what, detail === undefined ? '' : `— ${detail}`); }
};

const stack = await startStack({ numBlocks: 8, keepDir: true });

/*
 * FIVE SAMPLES, SYNTHESISED, AND ALL DIFFERENT.
 *
 * The repo ships two WAVs and one of them is the probe every other sampler suite uses. Loading
 * the same file five times would make a golden that cannot tell one slot from another — a render
 * that played slot 1 five times would be byte-identical to the right one. So each sample is a
 * different frequency AND a different length, which is what lets the per-window audibility check
 * below say "all five reached the mix" rather than "something did".
 *
 * Written by hand rather than generated by a tool, because the bytes have to be stable: a
 * generator with a random phase or a dithered tail would make the golden move on its own. Integer
 * arithmetic throughout, no dither, no fade — a click at each edge is fine here and a float
 * rounding difference between machines would not be.
 */
const RATE = 44100;
const SAMPLES = [
  { name: 's1.wav', hz: 220, ms: 400 },
  { name: 's2.wav', hz: 330, ms: 300 },
  { name: 's3.wav', hz: 440, ms: 250 },
  { name: 's4.wav', hz: 550, ms: 200 },
  { name: 's5.wav', hz: 660, ms: 150 },
];
for (const s of SAMPLES) {
  const n = Math.round(RATE * s.ms / 1000);
  const data = Buffer.alloc(n * 2);
  for (let i = 0; i < n; i++) {
    // A square wave from integer arithmetic: no Math.sin, so the bytes are the same on any
    // machine that runs this file, and the harmonics make each pitch trivially separable.
    const period = Math.round(RATE / s.hz);
    const v = (i % period) < (period >> 1) ? 12000 : -12000;
    data.writeInt16LE(v, i * 2);
  }
  const head = Buffer.alloc(44);
  head.write('RIFF', 0); head.writeUInt32LE(36 + data.length, 4); head.write('WAVE', 8);
  head.write('fmt ', 12); head.writeUInt32LE(16, 16); head.writeUInt16LE(1, 20);
  head.writeUInt16LE(1, 22); head.writeUInt32LE(RATE, 24);
  head.writeUInt32LE(RATE * 2, 28); head.writeUInt16LE(2, 32); head.writeUInt16LE(16, 34);
  head.write('data', 36); head.writeUInt32LE(data.length, 40);
  writeFileSync(join(stack.dir, s.name), Buffer.concat([head, data]));
}

const browser = await chromium.launch({ channel: 'chrome' });
const page = await browser.newPage({ viewport: { width: 1680, height: 980 } });
const errors = [];
page.on('pageerror', (e) => { if (!errors.includes(e.message)) errors.push(e.message); });
await page.goto(stack.url, { waitUntil: 'load' });
await page.waitForFunction(() => window.__uni && window.__uni.canSend(), null,
                           { timeout: 12000 }).catch(() => {});
await page.waitForTimeout(1200);

const said = [];
const run = async (c) => {
  const r = await page.evaluate((x) => window.__uni.run(x), c);
  said.push(`${c} -> ${JSON.stringify(r).slice(-90)}`);
  return r;
};

// ---------------------------------------------------------------------------
// BUILD THE SONG THROUGH THE UI. No daw-cli, no hand-written project — the owner's ask is that
// the samples are tracked VIA THE UI, and a fixture written to disk would test the format
// rather than the surface.
// ---------------------------------------------------------------------------
const T = 0;
await run('new rendersong');
await page.waitForTimeout(2500);
/*
 * A PROJECT MUST BE LOADED BEFORE A BARE SAMPLE NAME MEANS ANYTHING. `resolveSourcePath` joins
 * a relative name with the loaded project's directory, and with none loaded that is empty — the
 * source decodes to zero frames and every structural fact still looks right. `new` is what makes
 * the five names above resolve, which is why it comes before the sampler rather than after.
 */
await run(`sampler ${T}`);
await page.waitForTimeout(1500);
for (const s of SAMPLES) {
  await run(`load-sample ${T} 0 ${s.name}`);
  await page.waitForTimeout(1200);
}

const kit = await page.evaluate(async (t) => {
  for (let i = 0; i < 60; i++) {
    window.__uni.samplerKit(t, 0);
    const k = window.__uni.samplerKitCached(t, 0);
    if (k && k.slots && k.slots.length >= 5) return k;
    await new Promise((r) => setTimeout(r, 150));
  }
  return window.__uni.samplerKitCached(t, 0);
}, T);
check(kit && kit.slots && kit.slots.length === SAMPLES.length,
      `all ${SAMPLES.length} samples load, one slot each`,
      JSON.stringify(kit && kit.slots && kit.slots.map((s) => s.slot)));
/*
 * THE SLOT IDS, kept for the mapping below.
 *
 * The slots are NOT spread across keys here, which is where an earlier version did it. They are
 * spread AFTER the keyboard has written its notes, onto the pitches the keys actually produced —
 * so this file never has to know the key map, and a change to it would not turn into a golden
 * mismatch reported as an audio regression.
 */
const slotIds = kit && kit.slots ? kit.slots.map((s) => s.slot).sort((a, b) => a - b) : [];
// The lengths must differ, or the audibility check below cannot tell the slots apart either.
const frames = kit && kit.slots ? kit.slots.map((s) => s.frames) : [];
check(frames.length === SAMPLES.length && new Set(frames).size === SAMPLES.length
      && frames.every((f) => f > 0),
      'and the five decode to five DIFFERENT lengths — a golden built from one sample five '
      + 'times could not tell a dropped voice from a played one', JSON.stringify(frames));

/*
 * ONE NOTE PER SAMPLE, EIGHT ROWS APART, TYPED ON THE TRACKER'S OWN KEYBOARD.
 *
 * KEYSTROKES, NOT `note <pitch>`. The first version used the console verb, which is A UI surface
 * but not THE one: the ask was that the samples are tracked INTO THE TRACKER, and a `note`
 * command bypasses edit mode, the grid focus, the key map, the octave and the cursor's column —
 * every part of the path a person actually uses. A suite that drives the console proves the
 * console works.
 *
 * z x c v b at octave 4 are the white keys C D E F G. THE PITCHES ARE READ BACK RATHER THAN
 * ASSUMED: this file has no business knowing NOTE_KEYS, and a hardcoded 48 would turn a change
 * to the key map into a golden mismatch reported as an audio regression.
 *
 * Eight rows at zoom 1 is 8 x 240000 = 1,920,000 nanoticks — TWO BEATS, one second at 120 bpm.
 * I first wrote "half a beat" here and measured five contiguous 250 ms windows against it; three
 * landed in the silence between notes and the suite reported the render as dropping voices it
 * had played perfectly. The spacing and the window stride are the same number, which is why they
 * are one constant below rather than two.
 *
 * Every sample is shorter than the gap (400 ms at the longest), so each note owns its window
 * outright and energy in all five is a per-voice claim rather than a claim about the mix.
 */
await run('zoom 1');
await run('oct 4');
const NOTE_KEYS_USED = ['z', 'x', 'c', 'v', 'b'];
{
  /*
   * THE GRID HAS TO HAVE THE KEYBOARD, and edit mode has to be on, or the keys audition instead
   * of writing. Both are the state a person is in and neither is implied by the cursor being
   * somewhere — `state.focus` follows clicks, so the click is part of the gesture.
   */
  const cell = await page.evaluate(() => {
    const host = document.getElementById('tracker').getBoundingClientRect();
    for (const e of document.querySelectorAll('.tk-track .tk-cell')) {
      const r = e.getBoundingClientRect();
      if (r.width < 5 || r.y < host.y + 60 || r.y > host.y + host.height - 60) continue;
      const x = r.x + r.width / 2, y = r.y + r.height / 2;
      const top = document.elementFromPoint(x, y);
      if (top && (top === e || e.contains(top))) return { x, y };
    }
    return null;
  });
  check(!!cell, 'there is a reachable tracker cell to click into');
  if (cell) await page.mouse.click(cell.x, cell.y);
  await page.waitForTimeout(300);
  if (!(await page.evaluate(() => window.__uni.state().editMode))) {
    await page.keyboard.press('Meta+e');
    await page.waitForTimeout(300);
  }
  check(await page.evaluate(() => window.__uni.state().editMode),
        'and edit mode is on, so a note key WRITES rather than auditions');

  for (let i = 0; i < NOTE_KEYS_USED.length; i++) {
    await run(`goto ${i * 8} ${T}`);
    await page.waitForTimeout(200);
    await page.keyboard.press(NOTE_KEYS_USED[i]);
    await page.waitForTimeout(600);
  }
}
await page.waitForTimeout(1200);

/*
 * WHAT THE KEYBOARD ACTUALLY WROTE, and the slots follow IT rather than the other way round.
 *
 * `load-sample` mints every slot on C1 fixed-pitch, so five samples answer one note until they
 * are moved. Moving them to the pitches the keys produced — read back, not assumed — is what
 * makes each note reach its own sample, and it keeps this file ignorant of the key map.
 *
 * All three of keylow/keyhigh/root, because a zone whose low is above its high never matches and
 * a root left at 36 would transpose every sample by the distance it moved. Root == the played
 * key means no transposition, which is what makes the five windows comparable.
 */
const typed = await page.evaluate((t) => {
  const all = window.__uni.notes() || [];
  return all.filter((n) => n.tr === t).map((n) => n.p).sort((a, b) => a - b);
}, T);
check(typed.length === SAMPLES.length && new Set(typed).size === SAMPLES.length,
      'five keystrokes wrote five notes on five distinct pitches',
      JSON.stringify(typed));
const keys = typed;
if (slotIds.length === SAMPLES.length && keys.length === SAMPLES.length) {
  for (let i = 0; i < slotIds.length; i++) {
    await run(`slot ${T} 0 ${slotIds[i]} keylow ${keys[i]}`);
    await run(`slot ${T} 0 ${slotIds[i]} keyhigh ${keys[i]}`);
    await run(`slot ${T} 0 ${slotIds[i]} root ${keys[i]}`);
  }
}
await page.waitForTimeout(900);
const spread = await page.evaluate(async (t) => {
  window.__uni.samplerKit(t, 0);
  await new Promise((r) => setTimeout(r, 600));
  const k = window.__uni.samplerKitCached(t, 0);
  return k && k.slots ? k.slots.map((s) => [s.slot, s.keyLow, s.keyHigh, s.root]) : null;
}, T);
check(spread && spread.every((x) => x[1] === x[2] && x[2] === x[3])
      && new Set(spread.map((x) => x[1])).size === SAMPLES.length,
      'and every slot moved onto one of them, so a note reaches its own sample and not four '
      + 'others', JSON.stringify(spread));
/*
 * AND THE NOTES ARE STILL THERE AFTER ALL THAT SLOT WORK.
 *
 * Fifteen `slot` commands went past between the keystrokes and here, each one a track edit the
 * engine versions. This re-reads rather than trusting the earlier read: a note store that
 * dropped a note under a concurrent edit would leave four windows sounding and one silent, which
 * the per-window check below would report as a dropped VOICE rather than a dropped note.
 */
const written = await page.evaluate((t) => {
  // `tr`/`p`, not `track`/`pitch` — the read-back's own names. Filtering on the fixture's names
  // matches nothing and reports an empty tracker that is in fact full.
  const all = window.__uni.notes() || [];
  return all.filter((n) => n.tr === t).map((n) => n.p).sort((a, b) => a - b);
}, T);
check(written.length === SAMPLES.length
      && written.every((p, i) => p === keys[i]),
      'the five typed notes are still on the five pitches after the slots were mapped',
      `${JSON.stringify(written)} vs ${JSON.stringify(keys)}`);

await run('save rendersong');
await page.waitForTimeout(3000);
check(existsSync(join(stack.dir, 'rendersong.uniproj.json')), 'and the song is on disk');

/*
 * ...AND A SECOND SONG WITH FOUR OF THE FIVE NOTES DELETED, saved under its own name.
 *
 * This is the control for the golden: a project that is deliberately different has to render
 * different bytes, or "the wav equals the golden" would also pass with a render that ignored the
 * song entirely.
 *
 * Built THROUGH THE UI like the first one. The earlier version edited the saved JSON instead and
 * found zero notes to remove — notes live in the clip store, not on the placement, so
 * `placements[0].notes` is empty in a correctly saved file. A control that silently changed
 * nothing would have rendered identical bytes and reported the comparison blind.
 */
for (let i = 1; i < SAMPLES.length; i++) {
  await run(`goto ${i * 8} ${T}`);
  await page.waitForTimeout(150);
  await run('del');
  await page.waitForTimeout(400);
}
const left = await page.evaluate((t) => (window.__uni.notes() || []).filter((n) => n.tr === t).length, T);
check(left === 1, 'the control song really has one note left, not five',
      `${left} notes after four deletes`);
await run('save rendershort');
await page.waitForTimeout(3000);
await browser.close();
stack.stop();
// The stack's engine has to be gone before another one opens the same project directory: two
// engines on one segment is the failure this repo spent a night misreading as a crash, and the
// isolation is derived from DAW_UI_SHM_NAME, so the render below gets its own.
await new Promise((r) => setTimeout(r, 1500));

// ---------------------------------------------------------------------------
// RENDER IT OFFLINE, TWICE. No audio device, no wall clock, no capture window.
// ---------------------------------------------------------------------------
const render = (name) => {
  const out = join(stack.dir, `${name}.wav`);
  try { unlinkSync(out); } catch { /* absent is the normal case */ }
  execFileSync(join(ROOT, 'build', 'daw_engine'),
               ['--project', 'rendersong', '--render', name, '--run-seconds', '6'],
               { cwd: join(ROOT, 'build'),
                 env: { ...process.env,
                        DAW_PROJECT_DIR: stack.dir,
                        DAW_HOST_BINARY: join(ROOT, 'build', 'juce_host_process'),
                        DAW_UI_SHM_NAME: `/samprend_${process.pid}_${name}` },
                 stdio: ['ignore', 'pipe', 'pipe'], timeout: 120000 });
  return existsSync(out) ? readFileSync(out) : null;
};

let a = null, b = null;
try { a = render('take_a'); } catch (e) { check(false, 'the offline render runs', String(e).slice(0, 200)); }
check(a && a.length > 44, 'the offline render writes a WAV', a ? `${a.length} bytes` : 'nothing');

if (a) {
  /*
   * 1. NOT SILENT. The check that has to come first, because a golden of silence compares equal
   *    to a broken engine forever — and this repo has already spent a night reading a silent
   *    capture as a bug in the instrument.
   */
  const pcm = (buf) => {
    // The data chunk, FOUND rather than assumed at offset 44: a WAV may carry LIST or fact
    // chunks before it, and reading a header as samples is how a silent file looks loud.
    let o = 12;
    while (o + 8 <= buf.length) {
      const id = buf.toString('ascii', o, o + 4), sz = buf.readUInt32LE(o + 4);
      if (id === 'data') return buf.subarray(o + 8, Math.min(buf.length, o + 8 + sz));
      o += 8 + sz + (sz & 1);
    }
    return buf.subarray(44);
  };
  const d = pcm(a);
  let peak = 0, nonzero = 0;
  for (let i = 0; i + 1 < d.length; i += 2) {
    const v = Math.abs(d.readInt16LE(i));
    if (v > peak) peak = v;
    if (v > 64) nonzero++;
  }
  check(peak > 1000, 'the render is NOT SILENT — the check every other line here depends on',
        `peak ${peak}, ${nonzero} samples above the noise floor`);

  /*
   * 2. EVERY SAMPLE IS AUDIBLE IN ITS OWN WINDOW.
   *
   * Byte equality would be satisfied by a render that dropped four voices, as long as it dropped
   * them the same way every time. The notes are half a beat apart at 120 bpm, so each one owns a
   * 250 ms window; energy in all five is what says all five reached the mix.
   *
   * The FIRST window is measured from the first non-silent sample rather than from frame 0: the
   * render's pre-roll is deterministic but not zero-length, and hardcoding an offset would make
   * this check depend on a startup detail it is not about.
   */
  const CH = 2, FRAME = CH * 2;
  let first = -1;
  for (let i = 0; i + 1 < d.length; i += 2) {
    if (Math.abs(d.readInt16LE(i)) > 64) { first = Math.floor(i / FRAME); break; }
  }
  // The note spacing, in frames: 8 rows x 240000 nanoticks = 2 beats = 1s at 120 bpm. The window
  // is the first 300 ms of each, which is inside the gap and covers even the 400 ms sample's
  // attack. One constant for the stride so it cannot drift from the notes it is measuring.
  const strideFrames = RATE * 1;
  const winFrames = Math.round(RATE * 0.3);
  const energies = [];
  for (let k = 0; k < SAMPLES.length; k++) {
    const from = (first + k * strideFrames) * FRAME, to = Math.min(d.length, from + winFrames * FRAME);
    let e = 0;
    for (let i = from; i + 1 < to; i += 2) e += Math.abs(d.readInt16LE(i));
    energies.push(Math.round(e / Math.max(1, (to - from) / 2)));
  }
  check(first >= 0 && energies.every((e) => e > 50),
        `all ${SAMPLES.length} notes are audible in their own window — a render that dropped `
        + 'four voices would still match a golden of itself',
        `onset frame ${first}, mean |s| per window ${JSON.stringify(energies)}`);

  /*
   * 3. REPEATABLE IN THIS RUN. Asserted here and not only in offline_render_check.sh, because
   *    the golden below is worthless without it: a byte diff has to be attributable to the
   *    change rather than to a race in block ordering or host completion.
   */
  try { b = render('take_b'); } catch { /* reported by the check */ }
  check(b && a.equals(b), 'two renders of the same project are byte-identical',
        b ? `${a.length} vs ${b.length} bytes` : 'the second render produced nothing');

  /*
   * 4. THE COMPARISON DISCRIMINATES. A deliberately different project must render different
   *    bytes — otherwise "the wav equals the golden" would pass with the render ignoring the
   *    song entirely, which is exactly the shape of every green-with-the-bug-present check this
   *    project keeps finding.
   */
  let c = null;
  try {
    execFileSync(join(ROOT, 'build', 'daw_engine'),
                 ['--project', 'rendershort', '--render', 'take_c', '--run-seconds', '6'],
                 { cwd: join(ROOT, 'build'),
                   env: { ...process.env, DAW_PROJECT_DIR: stack.dir,
                          DAW_HOST_BINARY: join(ROOT, 'build', 'juce_host_process'),
                          DAW_UI_SHM_NAME: `/samprend_${process.pid}_c` },
                   stdio: ['ignore', 'pipe', 'pipe'], timeout: 120000 });
    const p = join(stack.dir, 'take_c.wav');
    c = existsSync(p) ? readFileSync(p) : null;
  } catch { /* reported by the check */ }
  check(left === 1 && c && !a.equals(c),
        'a song with four of the five notes removed renders DIFFERENT bytes — the comparison '
        + 'can tell two songs apart', `${c ? `${c.length} bytes` : 'no render'}`);

  // ---------------------------------------------------------------------------
  // WAV === GOLDEN.
  // ---------------------------------------------------------------------------
  if (!existsSync(BASE)) mkdirSync(BASE, { recursive: true });
  if (BLESS || !existsSync(GOLDEN)) {
    writeFileSync(GOLDEN, a);
    console.log(`  ${BLESS ? 'blessed' : 'created'} ${GOLDEN} (${a.length} bytes)`);
  } else {
    const want = readFileSync(GOLDEN);
    /*
     * THE GOLDEN DID NOT MOVE WHEN THE NOTE ENTRY CHANGED, and that is correct rather than
     * suspicious — worth writing down, because "I changed every pitch and the bytes are
     * identical" is exactly what a golden disconnected from its input looks like.
     *
     * The pitches went from 36,38,40,42,44 (the console verb) to 48,50,52,53,55 (z x c v b at
     * octave 4). Each slot's ROOT follows its key, so every sample still plays at its own root:
     * zero semitones of transposition either way, same audio. What the render responds to is
     * WHICH SLOT sounds and WHEN, and the "four notes removed renders different bytes" check
     * above is what proves it responds at all.
     */
    if (a.equals(want)) check(true, 'wav === golden, byte for byte');
    else {
      // WHERE it differs, because "the bytes differ" is not a finding. A length change is a
      // structural difference (a note moved, the render length changed); a first-difference deep
      // in the data with the same length is a change to the sound itself.
      let at = -1;
      for (let i = 0; i < Math.min(a.length, want.length); i++) {
        if (a[i] !== want[i]) { at = i; break; }
      }
      const stray = join(here, 'out', 'sampler-render.wav');
      try { writeFileSync(stray, a); } catch { /* out/ may not exist on a fresh checkout */ }
      check(false, 'wav === golden, byte for byte',
            `${a.length} bytes vs ${want.length}; first difference at ${at} `
            + `(${at < 0 ? 'length only' : at < 44 ? 'in the header' : 'in the audio'}) `
            + `— listen to ${stray}, and --bless if the change was meant`);
    }
  }
}

check(errors.length === 0, 'and nothing threw in the browser', errors.slice(0, 3).join(' | '));
if (fail) console.log('\n' + said.slice(-8).join('\n'));
console.log(`\n${fail === 0 ? `ALL PASS (${pass} checks)` : `${fail} of ${pass + fail} FAILED`}`);
process.exit(fail === 0 ? 0 : 1);
