// THE STRUCTURAL COMPARER MUST SEE EVERYTHING THE SERIALIZER WRITES.
//
// Undo's "did this command change anything" test is DocumentHistory::commit. It has always been
// answered by serializing the whole document and comparing strings — correct by construction,
// because it is the same definition a SAVE uses, so the two cannot disagree about what a document
// is. Stage 3 replaces it with documentFieldsEqual, which walks the field lists and stops at the
// first difference.
//
// THAT SWAP IS A FIDELITY RISK, not a free speed-up. A field the serializer writes and the field
// lists forget makes commit() answer "nothing changed" for an edit that changed it: no version,
// no undo step, and Ctrl-Z stepping straight over the user's edit. Silent, permanent, and
// indistinguishable from a refused command. The field lists are hand-written across eleven
// structs, and a hand-written mirror of a hand-written serializer is exactly the shape that has
// cost the most here — two rules agreeing on NAMES and differing in BEHAVIOUR.
//
// SO THIS COMPARES THE ANSWERS, NOT THE LISTS. For every shipped preset, for every leaf in what
// the serializer actually writes: perturb that one leaf, parse it back, and require the comparer
// to call the two documents different. A field the walk cannot see fails here by name.
//
// THE ALLOWED DIVERGENCES ARE DERIVED FROM THE SAME SOURCE, not from a list somebody maintains.
// FieldKind::Derived and ::Session fields are skipped by the comparer ON PURPOSE — hostSlotIndex
// is an index into this machine's plugin scan, and undo must not restore a session field (that
// bug wiped the loop region). A hand-kept exception list would rot the moment a field changed
// kind, so the visitor is asked which names those are and only they may compare equal.
//
// WHAT THIS DOES NOT PROVE: that the comparer says EQUAL only when the serializer does. That
// direction is the harmless one — a comparer that over-reports change records a redundant version
// rather than losing an edit — and it is covered by the round trip in the first case below.
//
// IT RUNS AS A SHRINK-ONLY RATCHET, because the answer on its first run was 29 blind fields and
// commit() therefore has NOT been switched to the comparer. A baseline file lists the fields
// known to be invisible today; the check fails if a NEW one appears, and it also fails if a
// listed one is no longer blind. The second half is the point — it makes the list impossible to
// leave stale, and it empties itself as the field lists are completed. When the baseline is empty
// the switchover is safe and this becomes an ordinary equality assertion.
//
// A list of known defects is not the same thing as a hand-maintained list of fields to ignore.
// This one is generated by the tool (--print-blind), shrinks only, and every entry is a bug.

#include <cstdio>
#include <fstream>
#include <set>
#include <sstream>
#include <string>
#include <vector>

#include <boost/property_tree/json_parser.hpp>
#include <boost/property_tree/ptree.hpp>

#include "apps/document_compare.h"
#include "apps/document_visitor_fields.h"
#include "apps/project_file.h"

namespace {

int fails = 0;
void fail(const std::string& what) {
  std::printf("  FAIL: %s\n", what.c_str());
  ++fails;
}

// ASK THE VISITOR which field names it deliberately ignores, at every level of the document. The
// names are collected recursively so a Derived field on a nested struct is known too; the walk
// records names only, because a JSON leaf is matched by its key.
struct SkippedNameCollector {
  std::set<std::string>* out;
  template <typename C, typename M>
  void field(const char* name, M C::*, daw::FieldKind kind = daw::FieldKind::Authored) {
    if (kind != daw::FieldKind::Authored) {
      out->insert(name);
    }
  }
};

template <typename T>
void collectSkipped(std::set<std::string>& out) {
  SkippedNameCollector collector{&out};
  daw::visitFields<T>(collector);
}

std::set<std::string> skippedFieldNames() {
  std::set<std::string> out;
  collectSkipped<daw::MixerSettings>(out);
  collectSkipped<daw::LaneQuantize>(out);
  collectSkipped<daw::TrackRoute>(out);
  collectSkipped<daw::TrackRouting>(out);
  collectSkipped<daw::Device>(out);
  collectSkipped<daw::ProjectPlacement>(out);
  collectSkipped<daw::ProjectClip>(out);
  collectSkipped<daw::ProjectTrack>(out);
  collectSkipped<daw::TrackChain>(out);
  collectSkipped<daw::ModLink>(out);
  collectSkipped<daw::ProjectDocument>(out);
  return out;
}

// Every (path, key) of a scalar leaf in the tree, so a mutation can be addressed precisely.
void collectLeaves(const boost::property_tree::ptree& tree, const std::string& prefix,
                   std::vector<std::pair<std::string, std::string>>& out) {
  if (tree.empty()) {
    return;
  }
  for (const auto& [key, child] : tree) {
    const std::string path = prefix.empty() ? key : prefix + "." + key;
    if (child.empty()) {
      out.emplace_back(path, key);
    } else {
      collectLeaves(child, path, out);
    }
  }
}

// Put a DIFFERENT value at `path`, whatever is there now. Numbers move by one, booleans invert,
// strings gain a suffix — chosen so the new value still parses as the same JSON type, because a
// mutation the deserializer rejects would test the parser rather than the comparer.
bool perturb(boost::property_tree::ptree& tree, const std::string& path) {
  const std::string value = tree.get<std::string>(path, "");
  if (value == "true") { tree.put(path, "false"); return true; }
  if (value == "false") { tree.put(path, "true"); return true; }
  if (!value.empty()) {
    // A number? Bump it. Leading '-' and one '.' allowed.
    bool numeric = true;
    bool dot = false;
    for (size_t i = 0; i < value.size(); ++i) {
      const char c = value[i];
      if (c == '-' && i == 0) { continue; }
      if (c == '.' && !dot) { dot = true; continue; }
      if (c < '0' || c > '9') { numeric = false; break; }
    }
    if (numeric) {
      try {
        const long double n = std::stold(value);
        std::ostringstream bumped;
        bumped.precision(17);
        bumped << (dot ? (n + 1.5L) : (n + 1.0L));
        tree.put(path, bumped.str());
        return true;
      } catch (...) {
        // fall through to the string case
      }
    }
  }
  tree.put(path, value + "_x");
  return true;
}

// Returns empty when the mutated tree cannot be written — a perturbation that produces
// unrepresentable JSON says nothing about the comparer, and letting the exception escape would
// abort the whole run on one preset (it did).
std::string serialize(const boost::property_tree::ptree& tree) {
  try {
    std::ostringstream out;
    boost::property_tree::write_json(out, tree);
    return out.str();
  } catch (const std::exception&) {
    return {};
  }
}

}  // namespace

int main(int argc, char** argv) {
  std::string baselinePath;
  bool printBlind = false;
  std::vector<std::string> presets;
  for (int argi = 1; argi < argc; ++argi) {
    const std::string arg = argv[argi];
    if (arg == "--baseline" && argi + 1 < argc) { baselinePath = argv[++argi]; continue; }
    if (arg == "--print-blind") { printBlind = true; continue; }
    presets.push_back(arg);
  }
  if (presets.empty()) {
    std::printf("usage: comparer_equivalence_tests [--baseline f] [--print-blind] "
                "<preset.uniproj.json> [more...]\n");
    return 2;
  }
  std::set<std::string> baseline;
  if (!baselinePath.empty()) {
    std::ifstream in(baselinePath);
    std::string line;
    while (std::getline(in, line)) {
      while (!line.empty() && (line.back() == '\r' || line.back() == ' ')) { line.pop_back(); }
      if (line.empty() || line[0] == '#') { continue; }
      baseline.insert(line);
    }
    if (baseline.empty()) {
      std::printf("  the baseline is EMPTY — every authored field is expected to be visible\n");
    }
  }
  std::set<std::string> blind;
  const std::set<std::string> skipped = skippedFieldNames();
  std::printf("  the visitor declares %zu non-authored field name(s) as deliberately invisible\n",
              skipped.size());

  size_t presetsRead = 0;
  size_t leavesTested = 0;
  size_t leavesSkipped = 0;
  for (const std::string& path : presets) {
    daw::ProjectDocument original;
    std::string error;
    if (!daw::loadProject(original, path, &error)) {
      fail("could not load preset " + path + ": " + error);
      continue;
    }
    ++presetsRead;

    // A document must equal itself through a save/load round trip, or nothing below means
    // anything: every "different" verdict would be indistinguishable from baseline noise.
    const std::string text = daw::serializeProject(original);
    boost::property_tree::ptree tree;
    {
      std::istringstream in(text);
      boost::property_tree::read_json(in, tree);
    }
    daw::ProjectDocument reparsed;
    if (!daw::deserializeProject(text, reparsed, &error)) {
      fail("could not re-parse the serialization of " + path + ": " + error);
      continue;
    }
    if (!daw::documentFieldsEqual(original, reparsed)) {
      // NAME THE PART THAT MOVED. "The document changed" sends the reader to diff two megabytes
      // of JSON; the track or clip index turns it into one object to look at.
      fail(path + ": a document does not compare equal to its own round trip. Something the "
                  "serializer writes does not survive being read back, so undo would restore a "
                  "different document than the one it recorded.");
      std::printf("        tracks %zu -> %zu, clips %zu -> %zu, markers %zu -> %zu\n",
                  original.tracks.size(), reparsed.tracks.size(), original.clips.size(),
                  reparsed.clips.size(), original.markers.size(), reparsed.markers.size());
      for (size_t i = 0; i < original.tracks.size() && i < reparsed.tracks.size(); ++i) {
        if (!daw::documentFieldsEqual(original.tracks[i], reparsed.tracks[i])) {
          std::printf("        track[%zu] (id %u) differs at field '%s'; %zu -> %zu devices\n", i,
                      original.tracks[i].trackId,
                      daw::documentFirstDifference(original.tracks[i], reparsed.tracks[i]).c_str(),
                      original.tracks[i].chain.devices.size(),
                      reparsed.tracks[i].chain.devices.size());
          for (size_t d = 0; d < original.tracks[i].chain.devices.size() &&
                             d < reparsed.tracks[i].chain.devices.size(); ++d) {
            if (!daw::documentFieldsEqual(original.tracks[i].chain.devices[d],
                                          reparsed.tracks[i].chain.devices[d])) {
              std::printf("          device[%zu] (id %u) differs at field '%s'\n", d,
                          original.tracks[i].chain.devices[d].id,
                          daw::documentFirstDifference(original.tracks[i].chain.devices[d],
                                                       reparsed.tracks[i].chain.devices[d]).c_str());
            }
          }
        }
      }
      for (size_t i = 0; i < original.clips.size() && i < reparsed.clips.size(); ++i) {
        if (!daw::documentFieldsEqual(original.clips[i], reparsed.clips[i])) {
          std::printf("        clip[%zu] (id %u) differs at field '%s'\n", i, original.clips[i].id,
                      daw::documentFirstDifference(original.clips[i], reparsed.clips[i]).c_str());
        }
      }
      continue;
    }

    std::vector<std::pair<std::string, std::string>> leaves;
    collectLeaves(tree, "", leaves);
    if (leaves.empty()) {
      fail(path + ": the serialization has no leaves — this preset asserts nothing");
      continue;
    }

    // ONE TEST PER FIELD, NOT PER ARRAY ELEMENT. A ptree array element has an empty key, so
    // 'tracks..device_chain..vst_ref.name' is the SHAPE of the field wherever it occurs; testing
    // the first occurrence answers "can the comparer see this field" and the hundredth adds
    // nothing. Without this the run is quadratic in document size — the stress presets have tens
    // of thousands of leaves and each test re-serializes the whole document.
    std::set<std::string> shapesTested;
    for (const auto& [leafPath, key] : leaves) {
      if (skipped.count(key) != 0) {
        ++leavesSkipped;
        continue;
      }
      if (!shapesTested.insert(leafPath).second) {
        continue;
      }
      boost::property_tree::ptree mutated = tree;
      if (!perturb(mutated, leafPath)) {
        continue;
      }
      const std::string mutatedText = serialize(mutated);
      if (mutatedText.empty() || mutatedText == text) {
        continue;  // the perturbation did not take; not a comparer finding
      }
      daw::ProjectDocument other;
      if (!daw::deserializeProject(mutatedText, other, &error)) {
        continue;  // the loader rejected it — tests the parser, not the comparer
      }
      // AND THE LOADER HAD TO KEEP THE CHANGE. A field the deserializer normalises away is not a
      // field the comparer failed to see, and counting it here would report the wrong component.
      if (daw::serializeProject(other) == daw::serializeProject(original)) {
        ++leavesSkipped;
        continue;
      }
      ++leavesTested;
      if (daw::documentFieldsEqual(original, other)) {
        blind.insert(leafPath);
      }
    }
  }

  std::printf("  %zu preset(s), %zu mutated leaf/leaves compared, %zu skipped "
              "(non-authored or normalised away)\n",
              presetsRead, leavesTested, leavesSkipped);

  if (printBlind) {
    for (const std::string& name : blind) { std::printf("%s\n", name.c_str()); }
  }
  for (const std::string& name : blind) {
    if (baseline.count(name) == 0) {
      fail("NEW blind field '" + name + "': the serializer calls two documents different and "
           "documentFieldsEqual calls them the same. Nothing may be added to this list — a field "
           "the comparer cannot see is an edit that would record no undo step once commit() is "
           "switched to it.");
    }
  }
  for (const std::string& name : baseline) {
    if (blind.count(name) == 0) {
      fail("'" + name + "' is listed as blind and is NOT blind any more. The baseline shrinks "
           "only, and it has to be told: a list that may stay stale is a list nobody trusts. "
           "Remove this line.");
    }
  }
  std::printf("  %zu field(s) the comparer cannot see (baseline holds %zu)\n",
              blind.size(), baseline.size());
  if (presetsRead == 0 || leavesTested == 0) {
    std::printf("comparer_equivalence: FAIL — nothing was actually compared\n");
    return 1;
  }
  if (fails) {
    std::printf("comparer_equivalence: FAIL (%d)\n", fails);
    return 1;
  }
  std::printf("comparer_equivalence: PASS — the comparer sees every authored field the "
              "serializer writes\n");
  return 0;
}
