use gpui::{actions, App, KeyBinding};

actions!(
    daw_app,
    [
        TogglePalette,
        OpenPluginPalette,
        PaletteUp,
        PaletteDown,
        PaletteConfirm,
        PaletteBackspace,
        PaletteClose,
        OpenScaleBrowser,
        TogglePlay,
        Undo,
        Redo,
        DeleteNote,
        SetLoopRange,
        PageZoomIn,
        PageZoomOut,
        ScrollUp,
        ScrollDown,
        ScrollPageUp,
        ScrollPageDown,
        ExpandSelectionUp,
        ExpandSelectionDown,
        ExpandSelectionBarUp,
        ExpandSelectionBarDown,
        ExpandSelectionLeft,
        ExpandSelectionRight,
        ToggleFollowPlayhead,
        ToggleHarmonyFocus,
        ColumnLeft,
        ColumnRight,
        CommitCellEdit,
        CancelCellEdit,
        FocusLeft,
        FocusRight,
        OpenJump,
        CopySelection,
        CutSelection,
        PasteSelection,
        PageCut,
        PageCopy,
        PagePaste
    ]
);

pub fn bind_keys(cx: &mut App) {
    cx.bind_keys([
        KeyBinding::new("cmd-p", OpenPluginPalette, None),
        KeyBinding::new("cmd-k", TogglePalette, None),
        KeyBinding::new("cmd-g", OpenJump, None),
        KeyBinding::new("cmd-shift-s", OpenScaleBrowser, None),
        KeyBinding::new("escape", PaletteClose, None),
        KeyBinding::new("up", PaletteUp, None),
        KeyBinding::new("down", PaletteDown, None),
        KeyBinding::new("shift-up", ExpandSelectionUp, None),
        KeyBinding::new("shift-down", ExpandSelectionDown, None),
        KeyBinding::new("cmd-shift-up", ExpandSelectionBarUp, None),
        KeyBinding::new("cmd-shift-down", ExpandSelectionBarDown, None),
        KeyBinding::new("pageup", ScrollPageUp, None),
        KeyBinding::new("pagedown", ScrollPageDown, None),
        KeyBinding::new("fn-up", ScrollPageUp, None),
        KeyBinding::new("fn-down", ScrollPageDown, None),
        KeyBinding::new("space", TogglePlay, None),
        KeyBinding::new("f", ToggleFollowPlayhead, None),
        KeyBinding::new("ctrl-h", ToggleHarmonyFocus, None),
        KeyBinding::new("enter", PaletteConfirm, None),
        KeyBinding::new("backspace", PaletteBackspace, None),
        KeyBinding::new("delete", DeleteNote, None),
        KeyBinding::new("cmd-l", SetLoopRange, None),
        KeyBinding::new("cmd-=", PageZoomIn, None),
        KeyBinding::new("cmd--", PageZoomOut, None),
        KeyBinding::new("cmd-c", CopySelection, None),
        KeyBinding::new("cmd-x", CutSelection, None),
        KeyBinding::new("cmd-v", PasteSelection, None),
        KeyBinding::new("shift-f3", PageCut, None),
        KeyBinding::new("shift-f4", PageCopy, None),
        KeyBinding::new("shift-f5", PagePaste, None),
        KeyBinding::new("cmd-z", Undo, None),
        KeyBinding::new("ctrl-z", Undo, None),
        KeyBinding::new("cmd-shift-z", Redo, None),
        KeyBinding::new("ctrl-shift-z", Redo, None),
        KeyBinding::new("left", FocusLeft, None),
        KeyBinding::new("right", FocusRight, None),
        KeyBinding::new("shift-left", ExpandSelectionLeft, None),
        KeyBinding::new("shift-right", ExpandSelectionRight, None),
        KeyBinding::new("[", ColumnLeft, None),
        KeyBinding::new("]", ColumnRight, None),
    ]);
}
